// Generated by RPG Maker.
// Do not edit this file directly.
var $plugins =
[
{"name":"WASD","status":true,"description":"","parameters":{}},
{"name":"3D_Maker","status":true,"description":"","parameters":{}},
{"name":"3D_Maker_Battles","status":true,"description":"","parameters":{}},
{"name":"FixPointerLock","status":true,"description":"Fix Pointer Lock SecurityError","parameters":{}}
];
